name: tests
on:
  #schedule:
  #  - cron: "0 0 * * *"
  push:
    branches:
      - master
      - main
    paths:
      - '*.c'
      - '*.h'
      - 'tests/*'
      - 'test'
      - '.github/workflows/*'
      - '.github/tools/*'
  pull_request:
    paths:
      - '*.c'
      - '*.h'
      - 'tests/*'
      - 'test'
      - '.github/*'
      - '.github/workflows/*'
      - '.github/tools/*'
  workflow_dispatch:
jobs:
  upstream_tests:
     runs-on: ubuntu:latest
     timeout-minutes: 150
     name: upstream tests
     steps:
     - uses: actions/checkout@v5
       if: ${{ github.event_name != 'schedule' }}
       with:
        fetch-depth: 0
     - uses: actions/checkout@v5
       if: ${{ github.event_name == 'schedule' }}
       with:
        ref: master
        fetch-depth: 0

     - name: Install build dependencies
       run: >-
         sudo apt-get install
         --yes --no-upgrade --no-install-recommends --no-install-suggests
         make gcc libudev-dev devscripts

     - name: Build mdadm
       run: make -j$(nproc) BINDIR=/usr/sbin

     - name: Install mdadm
       run: sudo make BINDIR=/usr/sbin install-bin

     - name: Check mdadm
       run: which mdadm

     - name: Fail
       run: false

     - name: 'Run tests'
       id: testing
       continue-on-error: true
       run: |
          cd ..
          vagrant ssh -c "cd /home/vagrant/host/mdadm && .github/tools/run_mdadm_tests.sh"

     - name: 'Copy logs to host machine'
       if: ${{ steps.testing.outcome == 'failure' }}
       run: |
          cd ..
          vagrant ssh -c "sudo mkdir -p /home/vagrant/host/logs && sudo mv /var/tmp/*.log /home/vagrant/host/logs"

     - name: "Save artifacts inspur5"
       if: ${{ steps.testing.outcome == 'failure' && env.RUNNER_NAME == 'inspur5' }}
       uses: actions/upload-artifact@v4
       with:
         name: "Logs from failed tests"
         path: /home/ci/actions-runner/_work/mdadm/logs/*.log

     - name: "Save artifacts inspur5-2"
       if: ${{ steps.testing.outcome == 'failure' && env.RUNNER_NAME == 'inspur5-2'}}
       uses: actions/upload-artifact@v4
       with:
         name: "Logs from failed tests"
         path: /home/ci/actions-runner-2/_work/mdadm/logs/*.log

     - name: "Clean logs"
       if: ${{ steps.testing.outcome == 'failure' }}
       run: |
          cd ..

          if [ "$RUNNER_NAME" == "inspur5" ]; then
            sudo rm /home/ci/actions-runner/_work/mdadm/logs/*.log
          else
            sudo rm /home/ci/actions-runner-2/_work/mdadm/logs/*.log
          fi

     - name: "Set failed"
       if: ${{ steps.testing.outcome == 'failure' }}
       run: exit 1

  cleanup:
    runs-on: self-hosted
    needs: [upstream_tests]
    steps:
      - name: Halt VM
        run:  |
          cd ..
          vagrant halt
